on:
  push:
    paths-ignore:
      - README.md
    branches:
      - master
  pull_request:
    paths-ignore:
      - README.md

name: Run tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Restore the node modules
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: modules-${{ hashFiles('**/package.json') }}

    - name: Install packages
      run: npm i --include-dev

    - name: Create the merged schema
      run: ./merge.sh

    - name: Run tests
      run: npm run test

    - name: Publish schemas
      if: {{ github.ref == 'ref/head/master' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        clean: false
        branch: gh-pages
        folder: merged
